### ISSUE TITLE
avalon_mm_bfm_pkg readdatavalid, wrong data

### ISSUE THREAD

**Issue by soundart** [UVVM/UVVM_All#10]
Hi,
there seems to be a problem in the avalon_mm_bfm if you configure it with use_readdatavalid        => true.

If avalon_mm_if.readdatavalid is high the bfm waits another rising edge and a bit and then samples avalon_mm_if.readdata.

I fixed this by commenting out the waits....

```
@@ -581,8 +582,8 @@ package body avalon_mm_bfm_pkg is
       if timeout then
         alert(config.max_wait_cycles_severity, proc_call & "=> Failed. Timeout waiting for readdatavalid");
       else
-        wait until rising_edge(clk);
-        wait_until_given_time_after_rising_edge(clk, config.clock_period/4);
+        --wait until rising_edge(clk);
+        --wait_until_given_time_after_rising_edge(clk, config.clock_period/4);
       end if;
 
     else  -- not waitrequest or readdatavalid - issue read, wait num_wait_states before finishing the read

```

Could you check please?
kind regards
  Frank

**Comment by UVVM** [comment]
Hi Frank,

You are absolutely correct.
This is changed in UVVM 2.0 to be released very soon.

Best regards
Espen

**Comment by soundart** [comment]
Hi Epsen,

thank you for the confirmation.

kind regards
  Frank

**Comment by soundart** [comment]
Workaround in git thanks!
