### ISSUE TITLE
What is the recommended value for max-delta-cycles to use UVVM?

### ISSUE THREAD

**Issue by Paebbels** [UVVM/UVVM_All#12]
UVVM needs a lot of iterations in a time step. So what is the recommended value for max-delta-cycles?

**Comment by UVVM** [comment]
The default is 1000. We recommend to set it to 5000.
(If you have an extreme system - pushing several hundred commands at the same time, you may need to go even higher. Wouldn't recommend such a test sequencer though ;-)

From Modelsim User Manual (assume similar setting is available in all simulators):
_The iteration limit default value is 1000. If you receive an iteration limit warning, first increase
the iteration limit and try to continue simulation. You can set the iteration limit from the
Simulate > Runtime Options menu or by modifying the IterationLimit variable in the
modelsim.ini. See modelsim.ini Variables for more information on modifying the modelsim.ini
file._

**Comment by Paebbels** [comment]
Thanks.

----------
Btw. GHDL can already compiled a few simple UVVM examples. So the new GHDL feature (unconstrained records) is working. We are now adding more tests.
