### ISSUE TITLE
Change log is incomplete

### ISSUE THREAD

**Issue by Paebbels** [UVVM/UVVM_All#14]
Hello,

the change log doesn't list that version 2.x removed OSVVM [removed in commit ab7ac88].
It should either state where to find OSVVM on GitHub or note that OSVVM is no longer supported / required for UVVM.

Moreover the change log dropped items for already tagged and release versions.

Kind regards
    Patrick

**Comment by andrefi** [comment]
Hi,

I've updated the changelog. We decided to remove the UVVM OSVVM directory for now, since it was quite outdated and not used in any of the examples we provide with UVVM. 

Best regards
Andre
