### ISSUE TITLE
AXI Stream testbench example

### ISSUE THREAD

**Issue by umarcor** [UVVM/UVVM_All#169]
I'm not being able to find any example about how to write a testbench using the AXI Stream verification components. I can see a `tb` subdir available for the UART VC (https://github.com/UVVM/UVVM/tree/master/bitvis_uart and https://github.com/UVVM/UVVM/tree/master/bitvis_vip_uart), but there is no such subdir in https://github.com/UVVM/UVVM/tree/master/bitvis_vip_axistream. Are such examples available in some other repo? Alternatively, I guess I could use the internal tests as a reference, but I can neither find those.

**Comment by umarcor** [comment]
> UVVM_SUPPLEMENTARY is now updated.

@mariuselv, thanks!

> UVVM_SUPPLEMENTARY is UVVM, but with all documentation sources (.docx) and verifications TBs.

Did you consider making UVVM a submodule of UVVM_SUPPLEMENTARY? I believe that'd make it easier for users to understand that the latter is a superset, along with making it easier for you to keep both repositories in sync.

> A few module testbenches are not possible to run because of missing DUTs that we use when testing our VIPs. Unfortunately we are not allowed to publish these due to license restrictions, but the testbenches and instantiations etc. are all there.

Is there a list of which are those DUTs (i.e. which VIPs are currently untested in the publicly available codebase)?

**Comment by mariuselv** [comment]
Hi @umarcor,
Sorry, I totally forgot your request. I will create a list so you and others can see which testbenches can be run and not.

Br,
Marius

**Comment by mariuselv** [comment]
Hi,
the testbenches for the following UVVM VIPs are not possible to run from UVVM_Supplementary:
- Bitvis VIP Avalon MM
- Bitvis VIP Avalon ST
- Bitvis VIP Ethernet
- Bitvis VIP I2C

There are some verification modules used by the testbenches for these VIPs that we are not allowed to publish, thus the testbenches can not be compiled and run. The VIP testbenches are included to show how the modules are tested and can be used as guidance for how to setup a test environment.

Best regards,
Marius

**Comment by UVVM** [comment]
Overview provided
