### ISSUE TITLE
vvc_generator.py

### ISSUE THREAD

**Issue by roynil** [UVVM/UVVM_All#27]
There is a typo in vvc_generator.py for READ command calling old store_result procedure:

                file_handle.write("        --     work.td_vvc_entity_support_pkg.store_result(instance_idx  => GC_INSTANCE_IDX,\n")
                file_handle.write("        --                                       cmd_idx       => v_cmd.cmd_idx,\n")
                file_handle.write("        --                                       data          => v_read_data);\n")

should be:

                file_handle.write("        --     work.td_vvc_entity_support_pkg.store_result(result_queue => result_queue,\n")
                file_handle.write("        --                                       cmd_idx       => v_cmd.cmd_idx,\n")
                file_handle.write("        --                                       result        => v_read_data);\n")

**Comment by UVVM** [comment]
Hi Ronny,
Thank you for your feedback! And, you are absolutely right! We are soon to push a new release and I will ensure the error is corrected.

Best regards
Marius Elvegård, Bitvis AS

Fra: Ronny Nilsson [mailto:notifications@github.com]
Sendt: torsdag 31. august 2017 08.07
Til: UVVM/UVVM_All <UVVM_All@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [UVVM/UVVM_All] vvc_generator.py (#27)


There is a typo in vvc_generator.py for READ command calling old store_result procedure:

            file_handle.write("        --     work.td_vvc_entity_support_pkg.store_result(instance_idx  => GC_INSTANCE_IDX,\n")

            file_handle.write("        --                                       cmd_idx       => v_cmd.cmd_idx,\n")

            file_handle.write("        --                                       data          => v_read_data);\n")

should be:

            file_handle.write("        --     work.td_vvc_entity_support_pkg.store_result(result_queue => result_queue,\n")

            file_handle.write("        --                                       cmd_idx       => v_cmd.cmd_idx,\n")

            file_handle.write("        --                                       result        => v_read_data);\n")

**Comment by UVVM** [comment]
This issue has been fixed in the latest release.
