### ISSUE TITLE
Simulation log flooded by "readdatavalid was active after <N> clocks"

### ISSUE THREAD

**Issue by alfstorm** [UVVM/UVVM_All#33]
When using the avalon_mm_bfm_package, I get "readdatavalid was active after \<N> clocks" for every read since message ID is set to 'config.id_for_bfm'. In my opinion, info about readdatavalid is only relevant if it fails, so may I suggest you change message ID to, let's say, ID_POS_ACK instead?

With regards,
Alf

**Comment by UVVM** [comment]
Hi Alf.
Thank you for your feedback!
I think your suggestion could be a good improvement of the BFM logging verbosity.

Best regards,
Marius
